money/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index),
    path('add/', views.add_transactions),
    path('update_matching/', views.update_matching),
    path('getting_started/', views.getting_started),
    path('find_outliers/', views.find_outliers),

    path('transactions/edit/', views.edit_transactions),
    path('transactions/', views.view_transactions),
    path('transactions/export/', views.export_transactions),
    path('transactions/import/', views.import_transactions),
    path('transactions/<int:transaction_id>/split/', views.split_transaction),
    path('transactions/<int:transaction_id>/unsplit/', views.unsplit_transaction),
    path('transactions/<int:transaction_id>/all_like_this/', views.all_like_this),
    path('transactions/<int:transaction_id>/edit/date/', views.edit_transaction_date),
    path('transactions/<int:transaction_id>/edit/description/', views.edit_transaction_description),
    path('transactions/<int:transaction_id>/edit/category/', views.edit_transaction_category),
    path('transactions/<int:transaction_id>/edit/account/', views.edit_transaction_account),
    path('transactions/<int:transaction_id>/edit/month/', views.edit_transaction_month),
    path('transactions/<int:transaction_id>/edit/properties/', views.edit_transaction_properties),
    path('transactions/<int:transaction_id>/delete/', views.delete_transaction),
    path('transactions/delete_zeroes/', views.delete_empty_transactions),

    path('categories/', views.view_categories),
    path('categories/<int:category_id>/', views.view_category),
    path('categories/<int:category_id>/page/<int:page>/', views.view_category),
    path('categories/<int:category_id>/delete/', views.delete_category),
    path('categories/add/', views.add_category),
    path('categories/new/', views.new_category),

    path('accounts/', views.view_accounts),
    path('accounts/<int:account_id>/', views.view_account),
    path('accounts/<int:account_id>/page/<int:page>/', views.view_account),
    path('accounts/add/', views.add_account),
    path('accounts/<int:account_id>/edit/name/', views.edit_account_name),
    path('accounts/<int:account_id>/delete/', views.delete_account),

    path('summary/', views.view_summary),
    path('summary/<str:period>/', views.view_summary),
    path('summary/<str:period>/<int:year>/', views.view_summary),
    path('summary/<str:period>/<int:year>/<int:month>/', views.view_summary),
    path('history/', views.view_history),

    path('settings/', views.settings),

    path('iphone-mammon.css', views.stylesheet, {'template': 'iphone-mammon.css'}),
    path('mammon.css', views.stylesheet, {'template': 'mammon.css'}),
    path('inline_edit.js', views.stylesheet, {'template': 'inline_edit.js', 'mimetype': 'text/javascript'}),
    path('input_overlay.js', views.stylesheet, {'template': 'input_overlay.js', 'mimetype': 'text/javascript'}),
    path('dialogs.js', views.stylesheet, {'template': 'dialogs.js', 'mimetype': 'text/javascript'}),
    path('input_overlay.css', views.stylesheet, {'template': 'input_overlay.css'}),
]

urls.py
from django.conf.urls import include
from django.urls import (
    path,
    re_path,
)
from django.views.i18n import JavaScriptCatalog

from django.views.static import serve
from iommi.admin import (
    Admin,
    Auth,
)

from authentication.views import (
    edit_user_password,
)
from views import (
    echo_headers,
    error_test,
)
from . import settings

urlpatterns = [
    path('', include('money.urls')),
    path('settings/password/', edit_user_password),

    path('registration/', include('mammon.registration.urls')),
    path('echo_headers/', echo_headers),
    path('bin2/gfskod', echo_headers),

    path('system/error_test/', error_test),

    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('admin/', include(Admin().urls())),

    # admin:
    # path(r'admin/', include(admin.site.urls)),
    # re_path(r'^media/(?P<path>.*)$', serve, {'document_root': '/var/www-python/kodare/django/contrib/admin/media'}),
    re_path(r'^site-media2/(?P<path>.*)$', serve, {'document_root': settings.DOCUMENT_ROOT + 'mammon/site-media'}),

    path('', include(Auth.urls()))
]

money/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import (
    gettext,
    ugettext_lazy as _,
)

# a little hack to get curias change password page to redirect to the root
from mammon.money import standardize_number, datetime_from_string


# noinspection PyUnusedLocal
def user_get_absolute_url(self):
    return '/'


User.get_absolute_url = user_get_absolute_url


class Account(models.Model):
    user = models.ForeignKey(User, verbose_name=_('User'), on_delete=models.CASCADE)
    name = models.CharField(blank=False, max_length=100, verbose_name=_('Name'))
    hide = models.BooleanField(default=False, verbose_name=_('Hide'))

    def __str__(self):
        return self.name

    def __lt__(self, other):
        if other is None:
            return self.name < ''
        return self.name < other.name


class Format(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    raw_format = models.CharField(blank=False, max_length=100, db_index=True)
    parse_format = models.CharField(blank=False, max_length=100)

    def __str__(self):
        return '%s: %s, %s' % (self.user, self.raw_format, self.parse_format)

    def parse_row(self, row):
        descriptions = []
        amount = None
        date = None
        for index, value in enumerate(self.parse_format):
            if value == '1':
                new_amount = standardize_number(row[index])
                assert not amount or not new_amount
                if new_amount:
                    amount = new_amount
            elif value == 'd':
                date = datetime_from_string(row[index])
            elif value == 't':
                descriptions.append(row[index])
        assert amount is not None
        assert date is not None
        assert len(descriptions) > 0
        return amount, date, ' '.join(descriptions)

    def compatible_with(self, classification):
        if classification == self.raw_format:
            return True
        for c, f in zip(classification, self.parse_format):
            if f == 'd' and c != f:
                return False
            if f == '1' and c != f:
                return False
        return True


class Category(models.Model):
    PERIODS = (
        (None, 'unknown'),
        (1, 'monthly'),
        (2, 'bi-monthly'),
        (3, 'quarterly'),
        (6, 'half-yearly'),
        (12, 'yearly'),
    )

    user = models.ForeignKey(User, verbose_name=_('User'), on_delete=models.CASCADE)
    account = models.ForeignKey(Account, null=True, blank=True, default=None, verbose_name=_('Account'), on_delete=models.CASCADE)
    name = models.CharField(max_length=100, verbose_name=_('Name'), blank=False)
    matching_rules = models.TextField(blank=True, verbose_name=_('Matching rules'))
    period = models.IntegerField(default=None, null=True, blank=True, choices=PERIODS, verbose_name=_('Period'))

    def add_rule(self, rule):
        self.matching_rules = '\n'.join([x for x in self.matching_rules.split('\n') if x] + [rule])

    def __lt__(self, other):
        return self.name < other.name

    def matches(self, transaction):
        for rule in self.matching_rules.splitlines():
            if rule.strip() != '':
                if rule.strip().lower() in transaction.description.lower():
                    return True
        return False

    def __str__(self):
        if self.name.strip() != '':
            return self.name
        else:
            return '<no name>'

    def get_absolute_url(self):
        return f'/categories/{self.pk}/'

    class Meta:
        ordering = ('name',)
        verbose_name_plural = gettext('Categories')


class Transaction(models.Model):
    user = models.ForeignKey(User, verbose_name=_('User'), on_delete=models.CASCADE)
    date = models.DateTimeField()
    month = models.DateField(null=True)
    description = models.TextField()
    amount = models.DecimalField(max_digits=19, decimal_places=2)
    category = models.ForeignKey(Category, blank=True, null=True, on_delete=models.SET_NULL)
    account = models.ForeignKey(Account, null=True, blank=True, default=None, on_delete=models.SET_NULL)
    virtual = models.BooleanField(default=False)  # means that this isn't the original transaction, but a part of a split transaction
    original_md5 = models.CharField(max_length=32, db_index=True)

    def __str__(self):
        from time import strftime

        return '%s %s %s %s' % (self.user, strftime('%Y-%m-%d', self.date.timetuple()), self.description, self.amount)

    class Meta:
        ordering = ('date', 'description')

    def get_absolute_url(self):
        return '/transactions/%s/' % self.pk

money/templates/money/all_like_this.html
{% load i18n %}{% load auth %}
<div id="id_all_like_this_dialog">
    <p style="font-size: 16px;">
        {% trans "Category" %}: <span id="id_select_category">{{ category }}</span><br />
        {% if account %}
            {% trans "Account" %}: <span id="id_select_account">{{ account }}</span>
        {% endif %}
    </p>

    <div style="white-space: nowrap">
        {{ description_spans }}
    </div>

    <span id="start_marker">&#x21A6;</span>
    <span id="end_marker">&#x21A4;</span>

    <div style="font-size: 12px; padding-top: 40px">
        {% blocktrans %}
            Press S to select the starting marker<br />
            Press E to select the ending marker<br />
            Hold down shift to move just one character at a time
        {% endblocktrans %}
    </div>

</div>

money/templates/money/cell_inline_edit.html
<span class="inline_editable" edit_url="/transactions/{{ row.id }}/edit/{{ cmd }}/" id="{{ row.id }}">{{ text }}</span>

money/templates/money/delete_range.html
{% extends 'base.html' %}
{% load i18n %}{% load auth %}

{% block content %}

<script type="text/javascript" src="http://eldmyra.se/media/js/core.js"></script>
<script type="text/javascript" src="http://eldmyra.se/media/js/admin/RelatedObjectLookups.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/calendar-picker.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/DateTimeShortcuts.js"></script>

{% if message %}<h3>{{ message }}</h3>{% endif %}

    <form action="" method="post">{% csrf_token %}
        <table>
            {{ form }}
        </table>
        
        <input type="submit" value="{% trans "Delete range" %}" class="button" />
    </form>
{% endblock %}

money/templates/money/find_outliers.html
{% extends "base.html" %}
{% load i18n %}

{% block extra_head %}
    <script type="text/javascript" src="{{ MEDIA_URL }}js/jquery.flot.pack.js"></script>
    <script type="text/javascript" src="{{ MEDIA_URL }}js/jquery.flot.time.min.js"></script>
    <style type="text/css">
    .tickLabel
    {
        white-space:nowrap;
    }
    </style>
{% endblock %}

{% block js_post_load %}{% endblock %}

{% block content %}

    <div id="legend"></div>

    <p>{% blocktrans %}This is category <a href="/transactions/?category={{ category.pk }}">{{ category }}</a>. It has the highest variation month over month. Click on the bars that you think look worst to see a list of transactions for that month. Then select which transactions should go into Exceptions (and split transactions that have abnormal size, placing one part in Exceptions).{% endblocktrans %}</p>

    <a href="?skip={{ skip_count }}" class="button">{% blocktrans %}I'm done with this category, show me the next worst{% endblocktrans %}</a>

    <div align="center">
        <div id="placeholder" style="width:600px; height:500px"></div>
    </div>

    {% for month, transactions in transactions_by_month %}
        <div id="{{ month.year }}-{{ month.month }}">
            <h1>{{ month.year }}-{{ month.month }}</h1>

            {% include "tri_table/list.html" %}
        </div>
    {% endfor %}

    <script id="source" language="javascript" type="text/javascript">

        var somePlot;
        var dataset;

        function togglePlot(seriesName)
        {
            var someData = somePlot.getData();
            for (var i = 0; i != someData.length; i++) {
                if (someData[i].label == seriesName) {
                    someData[i].bars.show = !someData[i].bars.show;
                    if (!someData[i].bars.show) {
                        someData[i].tmp = someData[i].data;
                        someData[i].data = [];
                    }
                    else {
                        someData[i].data = someData[i].tmp;
                    }
                }
            }
            somePlot.setData(someData);
            somePlot.setupGrid();
            somePlot.draw();
        }

        function create_timestamp(year, month, day)
        {
            var f = new Date();
            f.setFullYear(year, month, day);
            return f.getTime();
        }
        jQuery(function () {
            dataset = [
                {
                    title: '',
                    data:
                    [
                        {% for point in graph %}
                            [
                                create_timestamp({{ point.date.year }}, {{ point.date.month }} - 1, {{ point.date.day }}),
                                {{ point.amount }},
                                '{{ point.date.year }}-{{ point.date.month }}'
                            ],
                        {% endfor %}
                    ]
                }
            ];

            var placeholder = $("#placeholder");
            somePlot = $.plot(placeholder, dataset, {
                grid: { hoverable: true, clickable: true, backgroundColor: "white", borderWidth: 0, markings: [{color: 'white'}]},
                bars: { show: true, align: "center", barWidth: 1000*60*60*24*25, fill: true },
                xaxis: {
                    mode: "time",
                    tickColor: 'white'
                },
                yaxis: {
                    tickColor: 'white'
                },
                selection: { mode: "xy" },
                legend: {
                    container: $('#legend'),
                    labelFormatter: function(label) {
                        return '<a href="#" onClick="togglePlot(\''+label+'\'); return false;">'+label+'</a>';
                    }
                }
            });

            function showTooltip(x, y, contents) {
                $('<div id="tooltip">' + contents + '</div>').css( {
                    position: 'absolute',
                    display: 'none',
                    top: y + 5,
                    left: x + 5,
                    border: '1px solid #fdd',
                    padding: '2px',
                    'background-color': '#fee',
                    opacity: 0.80
                }).appendTo("body").fadeIn(200);
            }

            var previousPoint = null;
            placeholder.bind("plothover", function (event, pos, item) {
                var d = new Date();
                d.setTime(parseInt(pos.x.toFixed()));
                $("#x").text((d.getYear()+1900)+'-'+(d.getMonth()+1));
                $("#y").text(pos.y.toFixed(2));

                if (item) {
                    if (previousPoint != item.datapoint) {
                        previousPoint = item.datapoint;

                        $("#tooltip").remove();
                        var x = item.datapoint[0].toFixed(2),
                            y = item.datapoint[1].toFixed(2);
                        d.setTime(x);

                        showTooltip(item.pageX, item.pageY, y + ' (' + item.series.label + " " + (d.getYear()+1900)+'-'+(d.getMonth()+1)+')');
                    }
                }
                else {
                    $("#tooltip").remove();
                    previousPoint = null;
                }
            });

            placeholder.bind("plotclick", function (event, pos, item) {
                if (item) {
                    $('#' + dataset[0].data[item.dataIndex][2]).intoViewport();
                }
            });
        });
        </script>

{% endblock %}

money/templates/money/getting_started.html
{% extends "base.html" %}
{% load i18n %}{% load auth %}

{% block content %}

    <p>{% trans "Type the category name you want in the input field next to the description and hit enter to apply." %}</p>

    <a href="/" class="button">I'm done, the rest should be handled on a case by case basis</a>

    <h3>{% blocktrans %}{{ percent_done }}% of all transactions are categorized{% endblocktrans %}</h3>

    <p></p>

    {% if foo %}
        <form method="post">{% csrf_token %}
            <table>
                <thead>
                <tr>
                    <th>{% trans "Description" %}</th>
                    <th>{% trans "Count" %}</th>
                    <th>{% trans "Category" %}</th>
                </tr>
                </thead>

                <tbody>
                {% for description, count in foo %}
                    <tr>
                        <td class="description">{{ description }}</td>
                        <td>{{ count }}</td>
                        <td><input type="text" autocomplete="off"  name="{{ description }}"/></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <button>{% trans "submit" %}</button>
        </form>
    {% else %}
        {% blocktrans %}There are only transactions with unique descriptions left{% endblocktrans %}
    {% endif %}

    <script type="text/javascript">
        $(document).ready(function() {
            $($('input[type="text"]')[0]).focus();
            var inputs = $("input");
            inputs.inlineComplete({terms: [{% for category in categories %}"{{ category|escapejs }}"{% if not forloop.last %}, {% endif %}{% endfor %}]});
            $('form input').keydown(function (e) {
                if (e.keyCode === 13) {
                    $('form button').click();
                }
            });
        });
    </script>

{% endblock %}

money/templates/money/import.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <style type="text/css">
        textarea
        {
            height: 300px;
            width: 100%;
        }
    </style>

    <form action="" method="post">{% csrf_token %}
    
        <div id="id_post_data">
            <p>
                <button id="id_import" class="button">{% trans "Import transactions" %}</button>
            </p>

            <div class="content">
                <textarea id="id_data" rows="10" cols="40" name="data"></textarea>
            </div>
        </div>
        <span id="id_spinner" style="display: none">Processing...</span>
    </form>

{% endblock %}

money/templates/money/index_no_categories.html
{% load i18n %}
<p>
    {% blocktrans %}Now let's take care of the most common transactions. This is a list of the transactions where the description field occurs more than once.{% endblocktrans %}
</p>

<a href="/getting_started/" class="button">Let's do it!</a>

money/templates/money/invalid_transaction_log_format.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
	{% trans "Invalid transaction log format" %}
{% endblock %}

money/templates/money/split_transaction.html
{% load i18n %}{% load auth %}
<form method="post" id="id_split_form" data-amount="{{ transaction.amount }}" action="/transactions/{{ transaction.id }}/split/">{% csrf_token %}
    {% blocktrans %}Split "{{ transaction }}" into <input type="text" name="parts" value="" id="parts" onKeyUp="parts_changed()"/> parts{% endblocktrans %}

    <div>
        <input type="checkbox" id="equal_parts" name="equal_parts" onClick="parts_changed()"/><label for="equal_parts">{% trans "Equal parts" %}</label>
    </div>
    <div>
        <input type="checkbox" id="distribute" name="distribute" onClick="parts_changed()"/><label for="distribute">{% trans "Distribute parts across following months" %}</label>
    </div>

    <div id="part_list">
    </div>
    <div id="rest"></div>
</form>

money/templates/money/view_accounts.html
{% extends 'base.html' %}
{% load i18n %}{% load auth %}

{% block content %}
    {% if accounts %}
        <div style="text-align:left; display:table; margin-left:auto; margin-right:auto;">
        {% for account in accounts %}
            <a href="{{ account.id }}/">{{ account }}</a><br />
        {% endfor %}
        </div>
    {% else %}
        {% blocktrans %}No accounts defined yet. Go to <a href="/settings/">settings</a> to define accounts.{% endblocktrans %}
    {% endif %}
{% endblock %}

money/templates/money/view_categories.html
{% extends 'base.html' %}
{% load i18n %}{% load auth %}

{% block content %}
    {% if categories %}
        <div style="text-align:left; display:table; margin-left:auto; margin-right:auto;">
        {% for category in categories %}
            <a href="{{ category.id }}/">{{ category }}</a><br />
        {% endfor %}
        </div>
    {% else %}
        {% blocktrans %}No categories defined yet. <a href="/add/">Add some transactions</a> then go to the <a href="/">Home</a> page to create categories.{% endblocktrans %}
    {% endif %}
{% endblock %}

money/templates/money/view_category.html
{% extends 'base.html' %}
{% load i18n %}{% load auth %}

{% block content %}
    <script type="text/javascript">
        function delete_group(id)
        {
            $('<div>{{ confirm_delete_message }}</div>').dialog({
                buttons: {
                    '{{ _("Cancel") }}': function() { $(this).dialog("close"); },
                    '{{ _("Delete") }}': function() {window.location = '{{ base_url }}delete/?next='+window.location;}
                }
            });
        }
    </script>

    <div>
        <span class="button" onClick="delete_group({{ group.id }})"><i class="fa fa-trash"></i> {{ delete_message }}</span>
    </div>

    <p></p>

    <form method="post">{% csrf_token %}
        <table class="form">
            {{ form }}
            <tr><td></td><td><input type="submit" value="{% trans "Save" %}" class="button"/></td></tr>
        </table>
    </form>
    
    <script>
        $(window).load(function() {
            $('#id_matching_rules').keyup(highlight);
            highlight();
        });
    </script>
{% endblock %}

money/templates/money/view_period.html
{% extends 'base.html' %}
{% load i18n %}{% load auth %}

{% block extra_head %}

    <link rel="prefetch" href="/summary/{{ period }}/{{ previous_year }}/{% if period == "month" %}{{ previous_month }}/{% endif %}" >
    {% if next_period %}
        <link rel="prefetch" href="/summary/{{ period }}/{{ next_year }}/{% if period == "month" %}{{ next_month }}/{% endif %}">
    {% endif %}

{% endblock %}

{% block content %}
	<script type="text/javascript">
		$(document).ready(function() {
			$('#change').click(function() {
				var url = '/summary/{{ period }}/' + $('#year').val() + '/';
				{% if period == "month" %}
					url += $('#month').val() + '/';
				{% endif %}
				window.location = url;
				return false;
			});
		});
	</script>
	
    <div>
    
    <a href="/summary/{{ period }}/{{ previous_year }}/{% if period == "month" %}{{ previous_month }}/{% endif %}" class="link-button"><i class="fa fa-chevron-circle-left"></i> {% trans "Previous period" %}</a>
    {% if next_period %}<a href="/summary/{{ period }}/{{ next_year }}/{% if period == "month" %}{{ next_month }}/{% endif %}" class="link-button">{% trans "Next period" %} <i class="fa fa-chevron-circle-right"></i></a>{% endif %}
    
    </div>

    <p></p>

    <form action=".">{% csrf_token %}
        <label for="year">{% trans "Period" %}:</label>
        <input id="year" name="year" value="{{ year }}" />
		{% if period == "month" %}
        	<input id="month" name="month" value="{{ month }}" />
		{% endif %}
        <button class="button" id="change">{% trans "Go to" %}</button>

        <div class="start-to-end-time">
            {{ start_time|date:"Y-m-d" }} - {{ end_time|date:"Y-m-d" }}
        </div>
    </form>

	{% if transactions %}
	<table style="margin-top: 10px;">
		<thead>
			<tr>
				<th>{% trans "Category" %}</th>
				<th class="amount">{% trans "Sum" %}</th>
				<th></th>
				{% if period == "year" %}
					<th class="amount">{% trans "Monthly average" %}</th>
                    <th class="amount">{% trans "Standard deviation" %}</th>
				{% endif %}
			</tr>
		</thead>
    	{% for account, categories in summary.items %}
			{% if account.name != " default" %}
				<tr><td colspan="5">&nbsp;</td></tr>
				<tr>
					<td colspan="5"><h3 style="text-align:center; margin: 4px;">{{ account }}</h3></td>
				</tr>
			{% endif %}
			{% for category, d in categories %}
	            {% if d.sum %}
	                <tr class="category_id_{{ category.id }} category_period_{{ category.period }}_month">
	                    <td>
                            <a href="/transactions/?-query%2Fquery=category%3D{% if category.pk == 0 %}null{% else %}%22{{ category }}%22{% endif %}%20and%20month>%3D{{ start_time|date:"Y-m-d" }}%20and%20month<{{ end_time|date:"Y-m-d" }}{% if account.id %}%20and%20account%3D{{ account }}{% endif %}">
                                {{ category }}
                            </a>
                        </td>
	                    <td class="amount">{{ d.sum|floatformat:2 }}</td>
	                    <td>
	                        <div style="width: {{ d.severity|multiply:200|add:2 }}px;" class="{% if d.sum < 0 %}loss{% else %}gain{% endif %}">&nbsp;</div>
	                    </td>
						{% if period == "year" %}
							<td class="amount">{{ d.sum|divide:monthly_average_divisor|floatformat:2 }}</td>
                            <td class="amount">{{ d.std_deviation|floatformat:0 }}</td>
                        {% endif %}
	                </tr>
	            {% endif %}
			{% endfor %}
        	<tr>
				<td><b>{% trans "Total" %}</b></td>
				<td class="amount {{ account.lossgain }}">{{ account.total|floatformat:2 }}</td>
				<td></td>
				{% if period == "year" %}
					<td class="amount {{ account.lossgain }}">{{ account.total|divide:monthly_average_divisor|floatformat:2 }}</td>
                    <td></td>
				{% endif %}
			</tr>
	    {% endfor %}

		{% if summary|length != 1 %}
			{% if summary|length != 0 %}
				<tr><td colspan="5">&nbsp;</td></tr>
			{% endif %}
    		<tr>
				<td><b>{% trans "Total" %}</b></td>
				<td class="amount {{ lossgain }}">{{ total|floatformat:2 }}</td>
				<td></td>
				{% if period == "year" %}
					<td class="amount {{ lossgain }}">{{ total|divide:monthly_average_divisor|floatformat:2 }}</td>
                    <td></td>
				{% endif %}
			</tr>
		{% endif %}
   	</table>

    {% if projected_transactions %}
        <p></p>

    	<div>
        	{% trans "Projected" %}: {{ projected_sum }}
        </div>

        <div>
            <a onClick="$('#projection_log').toggle();">{% trans "Details" %} <i class="fa fa-chevron-circle-down"></i></a>
		</div>

        <div id="projection_log" style="display:none;">
            {% include "tri_table/list.html" with table=projected_table%}
        </div>
    {% endif %}

	{% else %}
		<p>
			{% trans "No transactions for this period" %}
		</p>
	{% endif %}
    
{% endblock %}

money/templates/money/view_transaction_list.html
{% extends 'base.html' %}
{% load i18n %}{% load auth %}

{% block content %}
    {% include "tri_table/list.html" %}
{% endblock %}